// US State abbreviations and names
export const US_STATES = {
  AL: 'Alabama',
  AK: 'Alaska',
  AZ: 'Arizona',
  AR: 'Arkansas',
  CA: 'California',
  CO: 'Colorado',
  CT: 'Connecticut',
  DE: 'Delaware',
  FL: 'Florida',
  GA: 'Georgia',
  HI: 'Hawaii',
  ID: 'Idaho',
  IL: 'Illinois',
  IN: 'Indiana',
  IA: 'Iowa',
  KS: 'Kansas',
  KY: 'Kentucky',
  LA: 'Louisiana',
  ME: 'Maine',
  MD: 'Maryland',
  MA: 'Massachusetts',
  MI: 'Michigan',
  MN: 'Minnesota',
  MS: 'Mississippi',
  MO: 'Missouri',
  MT: 'Montana',
  NE: 'Nebraska',
  NV: 'Nevada',
  NH: 'New Hampshire',
  NJ: 'New Jersey',
  NM: 'New Mexico',
  NY: 'New York',
  NC: 'North Carolina',
  ND: 'North Dakota',
  OH: 'Ohio',
  OK: 'Oklahoma',
  OR: 'Oregon',
  PA: 'Pennsylvania',
  RI: 'Rhode Island',
  SC: 'South Carolina',
  SD: 'South Dakota',
  TN: 'Tennessee',
  TX: 'Texas',
  UT: 'Utah',
  VT: 'Vermont',
  VA: 'Virginia',
  WA: 'Washington',
  WV: 'West Virginia',
  WI: 'Wisconsin',
  WY: 'Wyoming',
  DC: 'District of Columbia',
};

// Common street type abbreviations and their standard forms
export const STREET_TYPES = {
  st: 'Street',
  str: 'Street',
  street: 'Street',
  ave: 'Avenue',
  av: 'Avenue',
  avenue: 'Avenue',
  blvd: 'Boulevard',
  boulevard: 'Boulevard',
  dr: 'Drive',
  drv: 'Drive',
  drive: 'Drive',
  rd: 'Road',
  road: 'Road',
  ln: 'Lane',
  lane: 'Lane',
  ct: 'Court',
  court: 'Court',
  pl: 'Place',
  place: 'Place',
  cir: 'Circle',
  circle: 'Circle',
  way: 'Way',
  pkwy: 'Parkway',
  parkway: 'Parkway',
  hwy: 'Highway',
  highway: 'Highway',
  ter: 'Terrace',
  terrace: 'Terrace',
  trl: 'Trail',
  trail: 'Trail',
  sq: 'Square',
  square: 'Square',
};

// Directional abbreviations
export const DIRECTIONS = {
  n: 'N',
  north: 'N',
  s: 'S',
  south: 'S',
  e: 'E',
  east: 'E',
  w: 'W',
  west: 'W',
  ne: 'NE',
  northeast: 'NE',
  nw: 'NW',
  northwest: 'NW',
  se: 'SE',
  southeast: 'SE',
  sw: 'SW',
  southwest: 'SW',
};

// Unit type abbreviations
export const UNIT_TYPES = {
  apt: 'Apt',
  apartment: 'Apt',
  suite: 'Suite',
  ste: 'Suite',
  unit: 'Unit',
  '#': 'Unit',
  floor: 'Floor',
  fl: 'Floor',
  room: 'Room',
  rm: 'Room',
};

// Validation status types
export const VALIDATION_STATUS = {
  VALID: 'valid',
  CORRECTED: 'corrected',
  UNVERIFIABLE: 'unverifiable',
  INVALID: 'invalid',
};
